change_pins: true
change_transport: false
change_node: false

transport:
  use_wifi: true
  agent_ip: 10.0.0.36
  agent_port: 8888
  wifi_ssid: ssid_name
  wifi_password: password

pins:
  - number: 26
    mode: digital_input

  - number: 14
    mode: digital_output

  - number: 33
    mode: analog_input

  - number: 25
    mode: analog_output

  - number: 0
    mode: analog_output

node:
  node_name: esp32
  service_name: set_config
  publisher_name: read_pins
  subcriber_name: write_pins
